-- MySQL Script generated by MySQL Workbench
-- Fri Apr 12 21:47:51 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Project
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Project
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Project` DEFAULT CHARACTER SET utf8 ;
USE `Project` ;

-- -----------------------------------------------------
-- Table `Project`.`purchaseOrder`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project`.`purchaseOrder` (
  `orderNo` INT NOT NULL AUTO_INCREMENT,
  `quantity` INT NOT NULL,
  `cost` INT NOT NULL,
  `DATESTAMP` DATE NULL DEFAULT NULL,
  `TIME` VARCHAR(8) NULL DEFAULT NULL,
  `IP` VARCHAR(15) NULL DEFAULT NULL,
  `BROWSER` TINYTEXT NULL DEFAULT NULL,
  `FORMID` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`orderNo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project`.`Supplier`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project`.`Supplier` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `Purchase Order_Order No.` INT NOT NULL,
  `DATESTAMP` DATE NULL DEFAULT NULL,
  `TIME` VARCHAR(8) NULL DEFAULT NULL,
  `IP` VARCHAR(15) NULL DEFAULT NULL,
  `BROWSER` TINYTEXT NULL DEFAULT NULL,
  `FORMID` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Supplier_Purchase Order_idx` (`Purchase Order_Order No.` ASC),
  CONSTRAINT `fk_Supplier_Purchase Order`
    FOREIGN KEY (`Purchase Order_Order No.`)
    REFERENCES `Project`.`purchaseOrder` (`orderNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project`.`Customer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project`.`Customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `fName` VARCHAR(45) NOT NULL,
  `lName` VARCHAR(45) NOT NULL,
  `gender` ENUM("Male", "Female") NOT NULL,
  `address` VARCHAR(45) NOT NULL,
  `phone` VARCHAR(15) NOT NULL,
  `DATESTAMP` DATE NULL DEFAULT NULL,
  `TIME` VARCHAR(8) NULL DEFAULT NULL,
  `IP` VARCHAR(15) NULL DEFAULT NULL,
  `BROWSER` TINYTEXT NULL DEFAULT NULL,
  `FORMID` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project`.`ShoppingCart`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project`.`ShoppingCart` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `item` INT NOT NULL,
  `quantity` INT NOT NULL,
  `DATESTAMP` DATE NULL DEFAULT NULL,
  `TIME` VARCHAR(8) NULL DEFAULT NULL,
  `IP` VARCHAR(15) NULL DEFAULT NULL,
  `BROWSER` TINYTEXT NULL DEFAULT NULL,
  `FORMID` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idShoppingCart_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project`.`Rental`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project`.`Rental` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `date` DATE NOT NULL,
  `quantity` INT NOT NULL,
  `returnDate` DATE NOT NULL,
  `Customer_id` INT NOT NULL,
  `DATESTAMP` DATE NULL DEFAULT NULL,
  `TIME` VARCHAR(8) NULL DEFAULT NULL,
  `IP` VARCHAR(15) NULL DEFAULT NULL,
  `BROWSER` TINYTEXT NULL DEFAULT NULL,
  `FORMID` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `idRental_UNIQUE` (`id` ASC),
  INDEX `fk_Rental_Customer1_idx` (`Customer_id` ASC),
  CONSTRAINT `fk_Rental_Customer1`
    FOREIGN KEY (`Customer_id`)
    REFERENCES `Project`.`Customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project`.`Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project`.`Product` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `category` VARCHAR(45) NOT NULL,
  `rentPrice` INT NOT NULL,
  `buyPrice` INT NOT NULL,
  `quantityStock` INT NOT NULL,
  `releavedate` DATE NOT NULL,
  `ShoppingCart_id` INT NULL DEFAULT 0,
  `Rental_id` INT NULL DEFAULT 0,
  `PurchaseOrder_orderNo` INT NULL DEFAULT 0,
  `DATESTAMP` DATE NULL DEFAULT NULL,
  `TIME` VARCHAR(8) NULL DEFAULT NULL,
  `IP` VARCHAR(15) NULL DEFAULT NULL,
  `BROWSER` TINYTEXT NULL DEFAULT NULL,
  `FORMID` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Product_ShoppingCart1_idx` (`ShoppingCart_id` ASC),
  INDEX `fk_Product_Rental1_idx` (`Rental_id` ASC),
  INDEX `fk_Product_Purchase Order1_idx` (`PurchaseOrder_orderNo` ASC),
  CONSTRAINT `fk_Product_ShoppingCart1`
    FOREIGN KEY (`ShoppingCart_id`)
    REFERENCES `Project`.`ShoppingCart` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_Rental1`
    FOREIGN KEY (`Rental_id`)
    REFERENCES `Project`.`Rental` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Product_Purchase Order1`
    FOREIGN KEY (`PurchaseOrder_orderNo`)
    REFERENCES `Project`.`purchaseOrder` (`orderNo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project`.`Employee`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project`.`Employee` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(45) NOT NULL,
  `address` VARCHAR(100) NOT NULL,
  `phoneNo` VARCHAR(15) NOT NULL,
  `DATESTAMP` DATE NULL DEFAULT NULL,
  `TIME` VARCHAR(8) NULL DEFAULT NULL,
  `IP` VARCHAR(15) NULL DEFAULT NULL,
  `BROWSER` TINYTEXT NULL DEFAULT NULL,
  `FORMID` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project`.`Store`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project`.`Store` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `genre` VARCHAR(45) NOT NULL,
  `direction` VARCHAR(45) NOT NULL,
  `quantity` VARCHAR(45) NOT NULL,
  `DATESTAMP` DATE NULL DEFAULT NULL,
  `TIME` VARCHAR(8) NULL DEFAULT NULL,
  `IP` VARCHAR(15) NULL DEFAULT NULL,
  `BROWSER` TINYTEXT NULL DEFAULT NULL,
  `FORMID` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project`.`PayStatement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project`.`PayStatement` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `datePeriod` DATE NOT NULL,
  `amount` INT NOT NULL,
  `ShoppingCart_id` INT NOT NULL,
  `Employee_id` INT NOT NULL,
  `DATESTAMP` DATE NULL DEFAULT NULL,
  `TIME` VARCHAR(8) NULL DEFAULT NULL,
  `IP` VARCHAR(15) NULL DEFAULT NULL,
  `BROWSER` TINYTEXT NULL DEFAULT NULL,
  `FORMID` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_PayStatement_ShoppingCart1_idx` (`ShoppingCart_id` ASC),
  INDEX `fk_PayStatement_Employee1_idx` (`Employee_id` ASC),
  CONSTRAINT `fk_PayStatement_ShoppingCart1`
    FOREIGN KEY (`ShoppingCart_id`)
    REFERENCES `Project`.`ShoppingCart` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PayStatement_Employee1`
    FOREIGN KEY (`Employee_id`)
    REFERENCES `Project`.`Employee` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project`.`Customer_has_Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project`.`Customer_has_Product` (
  `Customer_id` INT NOT NULL,
  `Product_id` INT NOT NULL,
  `DATESTAMP` DATE NULL,
  `TIME` VARCHAR(8) NULL,
  `IP` VARCHAR(15) NULL DEFAULT NULL,
  `BROWSER` TINYTEXT NULL DEFAULT NULL,
  `FORMID` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`Customer_id`, `Product_id`),
  INDEX `fk_Customer_has_Product_Product1_idx` (`Product_id` ASC),
  INDEX `fk_Customer_has_Product_Customer1_idx` (`Customer_id` ASC),
  CONSTRAINT `fk_Customer_has_Product_Customer1`
    FOREIGN KEY (`Customer_id`)
    REFERENCES `Project`.`Customer` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Customer_has_Product_Product1`
    FOREIGN KEY (`Product_id`)
    REFERENCES `Project`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Project`.`Store_has_Product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Project`.`Store_has_Product` (
  `Store_id` INT NOT NULL,
  `Product_id` INT NOT NULL,
  `DATESTAMP` DATE NULL DEFAULT NULL,
  `TIME` VARCHAR(8) NULL DEFAULT NULL,
  `IP` VARCHAR(15) NULL DEFAULT NULL,
  `BROWSER` TINYTEXT NULL DEFAULT NULL,
  `FORMID` VARCHAR(255) NULL DEFAULT NULL,
  PRIMARY KEY (`Store_id`, `Product_id`),
  INDEX `fk_Store_has_Product_Product1_idx` (`Product_id` ASC),
  INDEX `fk_Store_has_Product_Store1_idx` (`Store_id` ASC),
  CONSTRAINT `fk_Store_has_Product_Store1`
    FOREIGN KEY (`Store_id`)
    REFERENCES `Project`.`Store` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Store_has_Product_Product1`
    FOREIGN KEY (`Product_id`)
    REFERENCES `Project`.`Product` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
